-- 코드를 입력하세요
# SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, (SALES * PRICE) AS TOTAL_SALES 
#         FROM 
#         (SELECT B.*, A.AUTHOR_NAME FROM BOOK B
#         JOIN AUTHOR A
#         ON B.AUTHOR_ID = A.AUTHOR_ID) INFO
#         JOIN BOOK_SALES BS
#         ON INFO.BOOK_ID = BS.BOOK_ID
#         WHERE SALES_DATE LIKE '2022-01%'
#         GROUP BY AUTHOR_ID, CATEGORY
#         ORDER BY AUTHOR_ID, CATEGORY DESC;
        
        
SELECT A.AUTHOR_ID AS AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
FROM BOOK_SALES BS
JOIN BOOK B
ON BS.BOOK_ID = B.BOOK_ID
JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY A.AUTHOR_ID, CATEGORY
ORDER BY A.AUTHOR_ID, CATEGORY DESC;